Update Function for Production Deployment
cisagov/findings-data-import-lambda pull request #13
Opened 2019-10-30 14:54 UTC by mcdonnnj

This PR updates the lambda for deployment to the production environment. Changes include:
* Use hard coded directory names and changed `success_folder` and `error_folder` to `save_succeeded` and `save_failed` respectively. These values now represent booleans to determine if the input should be saved.
* Remove checking object name in lambda as it will be handled by the lambda's trigger instead.
* Reduce document validation down to the existence of two required fields instead of checking all fields against a list of allowed fields.
* Streamline database insertion into one method call.
* Track the number of documents actually processed.

2019-10-30 18:04 UTC, dav3r requested changes
No major issues, but I listed some smaller things that should be updated or at least considered.

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +  --save-succesded=SUCCEEDED  The directory name used for storing successfully
Typo in `--save-succeeded`

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +        field_map_object = s3_client.get_object(Bucket=s3_bucket, Key=field_map)
It may be worth logging a warning if the `field_map_object` is `None`.

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +                finding["RVA ID"] = rvaId
Do we need to do any validation on `rvaId` to attempt to ensure it's correct or do we take care of that elsewhere?

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +                ".json", f"_{str(datetime.datetime.now())}.json"
I'm not a huge fan of filenames (or S3 keys in this case) with spaces in them.  Perhaps use `strftime` to format to the timestamp?

Same thing below in the `save_failed` section.

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +                f"name {SUCCEEDED_FOLDER}"
This logging message should also mention `{succeeded_filename}` in some way (e.g. `"Moved {data_filename} to the success directory under folder name {SUCCEEDED_FOLDER} as {succeeded_filename}"`).

Same thing below in the `save_failed` section.

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +        logging.warning(f"Error Message {type(err)}: {err}")
Why not `logging.error` here?

2019-10-30 18:04 UTC, dav3r commented on fdi/findings_data_import.py
> +                logging.info(f"Error deleting file with error: {delete_error}")
Why not `logging.error` here?

2019-10-30 18:08 UTC, mcdonnnj commented on fdi/findings_data_import.py
> +                finding["RVA ID"] = rvaId
This is assumed to be taken care of manually in the filename. @mzack5020 has a branch he is working on to derive this from the JSON data on a per finding basis.

2019-10-30 18:30 UTC, dav3r commented on fdi/findings_data_import.py
> +                finding["RVA ID"] = rvaId
This is probably worth mentioning in a comment earlier where `rvaId` is initially set.

2019-10-30 18:45 UTC, mcdonnnj commented on fdi/findings_data_import.py
> +        field_map_object = s3_client.get_object(Bucket=s3_bucket, Key=field_map)
Tested and if the object does not exist an Access Denied error is thrown in the `get_object()` call.

2019-10-30 19:20 UTC, dav3r commented on fdi/findings_data_import.py
> +        field_map_object = s3_client.get_object(Bucket=s3_bucket, Key=field_map)
👍

2019-10-30 19:58 UTC, dav3r approved these changes

2019-11-01 13:01 UTC, mzack5020 approved these changes

2019-11-01 13:02 UTC, mzack5020 commented
We went over this in person on Wednesday so it was an easy review. Thank you, Nick.

2019-11-04 16:28 UTC, jsf9k approved these changes
This looks good to me.  I do agree with @dav3r about the need to add a comment in one place.

2019-11-04 16:28 UTC, jsf9k commented on fdi/findings_data_import.py
> +                finding["RVA ID"] = rvaId
I agree with @dav3r here.

2019-11-04 21:26 UTC, mcdonnnj commented on fdi/findings_data_import.py
> +                finding["RVA ID"] = rvaId
Resolved in 320a0bc ,  thanks for the feedback.

2019-11-04 21:31 UTC, merged